#ifndef __ANIM_ANMS_
#define __ANIM_ANMS_

#define FRAME0  1

#define	ANIM_SMASH		0
#define	ANIM_ANDA		1
#define	ANIM_ANDA1		2
#define	ANIM_DRIVE_H		3
#define	ANIM_MATE		4
#define	ANIM_REVES_L		5
#define	ANIM_SUELO_D		6
#define	ANIM_SUELO_I		7
#define	ANIM_LEVANTA		8
#define	ANIM_RECIBE		9
#define	ANIM_SAQUE		10
#define	ANIM_ANDA2		11
#define	ANIM_GIRO_IZQ		12
#define	ANIM_ESPERA		13
#define	ANIM_GIRO_DER		14
#define	ANIM_SALTODER		15
#define	ANIM_SALTOIZQ		16
#define	ANIM_REVES_LR		17
#define	ANIM_CORRE		18
#define	ANIM_REVES_MR		19
#define	ANIM_DRIVE_LR		20
#define	ANIM_DRIVE_MR		21
#define	ANIM_REVES_H		22
#define	ANIM_REVES_HR		23
#define	ANIM_DRIVE_L		24
#define	ANIM_DRIVE_M		25
#define	ANIM_DRIVE_HR		26
#define	ANIM_REVES_M		27
#define	ANIM_DRIVE_P		28
#define	ANIM_REVES_P		29
#define	ANIM_CORRER		30
#define	ANIM_ANDAR		31
#define	ANIM_ANDA3		32
#define	ANIM_DIAGONAL		33
#define	ANIM_ATRAS		34

#endif
